.PHONY: clean All

All:
	@echo "----------Building project:[ DataStructure_Project - Debug ]----------"
	@"$(MAKE)" -f  "DataStructure_Project.mk"
clean:
	@echo "----------Cleaning project:[ DataStructure_Project - Debug ]----------"
	@"$(MAKE)" -f  "DataStructure_Project.mk" clean
